pipeline {
    agent any

    stages {
        stage('Code') {
            steps {
                git 'https://github.com/manju9676/WildWeekender.git'
                // no need to cd here; subsequent stages will operate in the infra subdirectory
            }
        }
        stage('Terraform Init'){
            steps{
                dir('infra') {
                    sh 'terraform init'
                }
            }
        }
        stage('Terraform Plan'){
            steps{
                dir('infra') {
                    sh 'terraform plan -out=tfplan'
                }
            }
        }
        stage('Terraform Apply'){
            steps{
                dir('infra') {
                    sh 'terraform apply -auto-approve tfplan'
                }
            }
        }
    }
}