apiVersion: v1
kind: Secret
metadata:
  name: wild-weekender-secrets
  namespace: wild-weekender
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZGU5eWNoZGps
  CLOUDINARY_KEY: OTMxMjIzMTY3MjI5Mjc4
  CLOUDINARY_SECRET: WkJQb0V2bWlweTBGcGZvM2hkbDRHU19sOUpj
  MAPBOX_TOKEN: cGsuZXlKMUlqb2lZWGR6WVhwMWNtVmtaWFp2Y0hNaUxDSmhJam9pWTIxdGFHdGtjVFV5TUhkNWVqSndjelp0TjI4MWR6TmthU0o5LnRpaklmZnlYXy1oNC1mUlR4MGNSamc=
  DB_URL: bW9uZ29kYitzcnY6Ly9hZG1pbjphZG1pbjE0M0BteWNsdXN0ZXIubGpxYXh6aS5tb25nb2RiLm5ldC8/YXBwTmFtZT1teWNsdXN0ZXI=
