apiVersion: apps/v1
kind: Deployment
metadata:
  name: wild-weekender-deployment
  namespace: wild-weekender
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wild-weekender
  template:
    metadata:
      labels:
        app: wild-weekender
    spec:
      # affinity:
      #   podAntiAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       - labelSelector:
      #           matchLabels:
      #             app: wild-weekender
      #         topologyKey: kubernetes.io/hostname

      containers:
        - name: wild-weekender-container
          image: manju9676/wild_weekender:39
          ports:
            - containerPort: 3000

          envFrom:
            - secretRef:
                name: wild-weekender-secrets

          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5

          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
