apiVersion: v1
kind: Service
metadata:
  name: wild-weekender-service
  namespace: wild-weekender
spec:
  type: LoadBalancer
  selector:
    app: wild-weekender
  ports:
    - port: 80
      targetPort: 3000
