apiVersion: v1
kind: Secret
metadata:
  name: wild-weekender-jenkins-sa-secret
  namespace: wild-weekender
  annotations:
    kubernetes.io/service-account.name: wild-weekender-jenkins-sa
type: kubernetes.io/service-account-token